version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    working_directory: ~/zaobao
    steps:
      - checkout
      - run: yarn install
      - run: yarn lint:md
      - run: yarn lint:js
      - run: yarn test
      - run: yarn test:coverage
